### ISSUE TITLE
New user registration UI design 

### ISSUE THREAD

**Issue by Idaisugi** [cis350/team_14_cis_3500_project_repo#1]
As a new user, I want to log in to access my account information.

**Comment by Hmucyo** [comment]
Acceptance criteria:
- New user should be a Penn Student 
- Signing up with an email ending in "upenn.edu"
- Be able to set a unique username (no space in the username)
- Be able to set a password (and Confirm the password)
- Password requirement:
1. 8 characters
2. Numeric character
3. Special character.
